name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull image from docker
      run: sudo docker pull oscarenriqq/ec2-example-cicd:latest

    - name: delete old container
      run: sudo docker rm -f ec2-example-cicd || true

    - name: Run docker container
      run: sudo docker run -d -p 8080:80 --name ec2-example-cicd oscarenriqq/ec2-example-cicd:latest

    - name: Copy .env file
      run: sudo cp .env.example .env

    - name: Generate keys
      run: php artisan key:generate